<html>

<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <title>
        Хаффман - ошибка
    </title>

</head>

<body>

<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo">&nbsp;&nbsp;&nbsp;Алгоритм Хаффмана - ошибка</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="/">На главную</a></li>
            <li><a href="/huffman">Алгоритм Хаффмана</a></li>
            <li><a href="https://vk.com/httprequest">Заглянуть к автору</a></li>
        </ul>
    </div>
</nav>

<h2>Ошибка: ${error} </h2>
<h2>Путь: ${path} </h2>

<a href="/" class="waves-effect waves-light btn">На главную</a>

</body>

</html>