<html>

<head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <title>
        Алгоритмы - главная
    </title>

</head>

<body>

<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo">&nbsp;&nbsp;&nbsp;Алгоритмы - главная</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="https://vk.com/httprequest">Заглянуть к автору</a></li>
        </ul>
    </div>
</nav>

<div class="container">
    <table class="stripped center">
        <thead>
        <tr>
            <th>Доступные алгоритмы</th>
            <th>Действие</th>
        </tr>
        </thead>

        <tbody>
        <tr>
            <td>Алгоритм Хаффмана</td>
            <td><a class="waves-effect waves-light btn" href="/huffman">Перейти</a></td>
        </tr>
        <tr>
            <td>Алгоритм LZW + преобразование Б/У</td>
            <td><a class="waves-effect waves-light btn" href="/lzw">Перейти</a></td>
        </tr>
        </tbody>
    </table>
    <br/>&nbsp;
    <br/>&nbsp;
    <br/>&nbsp;
    <br/>&nbsp;
    <br/>&nbsp;
    Выберите алгоритм и нажмите "перейти"
</div>

</body>

</html>